# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=200)),
                ('dest_city', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='flight date')),
            ],
        ),
    ]
