# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_city',
            field=models.CharField(default='city', max_length=200),
        ),
    ]
