# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_airport_airport_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='dest_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_city', to='search.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_city', to='search.Airport'),
        ),
    ]
