# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20170519_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='arr_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='arrival datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='dept_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='depature datetime'),
            preserve_default=False,
        ),
    ]
