# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20170519_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('sexField', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('birthDate', models.DateField()),
                ('citizenship', models.CharField(max_length=200)),
                ('documentNum', models.CharField(max_length=200)),
                ('validTo', models.DateField()),
                ('idNum', models.CharField(max_length=200)),
                ('phone_country', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
