# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='citizenship',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='documentNum',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='idNum',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='second_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sexField',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='validTo',
            field=models.DateField(null=True),
        ),
    ]
