# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_passenger_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.IntegerField(choices=[('cash', 'cash'), ('card', 'card')], default=0, verbose_name='\u041e\u043f\u043b\u0430\u0442\u0430')),
                ('tickets_num', models.PositiveSmallIntegerField(default=0, verbose_name='\u0411\u0438\u043b\u0435\u0442\u044b')),
                ('tickets_txt', models.CharField(blank=True, default='', max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440\u0430 \u0431\u0438\u043b\u0435\u0442\u043e\u0432')),
                ('status', models.CharField(blank=True, default='BOOKED', max_length=15, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u041c\u0435\u0442\u043e\u0434 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('payment_id', models.CharField(blank=True, default='', max_length=50, verbose_name='ID \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('provider_code', models.CharField(db_index=True, default='', max_length=20, verbose_name='\u041a\u043e\u0434 \u0431\u0440\u043e\u043d\u0438')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
        ),
    ]
